### ISSUE TITLE
Support for OpenVINO 2022.2

### ISSUE THREAD

**Issue by scalers-ai** [intel/openvino-rs#47]
OpenVINO seems to have an updated installation method in 2022.2.

![image](https://user-images.githubusercontent.com/91742529/191887368-b1b22441-89ef-4deb-94a1-963a7f87c5c6.png)

**Comment by abrown** [comment]
Can you post a reproducer for how you got to that error message?

**Comment by scalers-ai** [comment]
It was a user error. Closing this issue.

**Comment by scalers-ai** [comment]
> Can you post a reproducer for how you got to that error message?

Deleting this as it was a user error.
