### ISSUE TITLE
Investigate switching to OpenVINO API 2.0

### ISSUE THREAD

**Issue by abrown** [intel/openvino-rs#53]
OpenVINO has a new API for accessing its functionality: API 2.0. The C API that these bindings rely on will soon be considered a legacy API. It would be worthwhile to consider switching the implementation to use the C API of API 2.0. A description of how to use some of the top-level structures can be found [here](https://docs.openvino.ai/nightly/openvino_docs_OV_UG_Integrate_OV_with_your_application.html).

**Comment by code-here** [comment]
hey, will these bindings support API 2.0 in future, are there any plans?

**Comment by abrown** [comment]
I think so, but it's dependent on a couple of things, mainly getting time to do this. Are you interested in helping out with that?

**Comment by abrown** [comment]
I've been informed that the legacy OpenVINO C API will be going away at the end of 2023. This means that switching to OpenVINO's 2.0 API will be necessary to continue binding to future versions of OpenVINO. To help out with this task, here are some steps I might follow:

- for context: find an installed `libopenvino_c.so` and list the new `ov_*` symbols: `nm <path> --dynamic --demangle | grep ov_`
- update the OpenVINO submodule (`crates/openvino-sys/upstream`) to a more recent version (i.e., the most recent release tag)
- find the new headers from which to generate bindings: [`src/bindings/c`](https://github.com/openvinotoolkit/openvino/blob/master/src/bindings/c/include/openvino/c/)
- modify the `codegen` task (`crates/xtask/src/codegen.rs`) to generate new Rust FFI shims to call these functions; then generate the new code with `cargo xtask codegen`
- walk through the `openvino` crate, mechanically changing as many `openvino_sys::ie_*` imports to their `openvino_sys::ov_*` equivalent; unfortunately, some of these changes cannot be mechanical and we will have to tweak certain functions (e.g., inputs and outputs are referenced by name) according to the [transition guide](https://docs.openvino.ai/2022.3/openvino_2_0_transition_guide.html)
- some of the examples and tests may need to be updated based on these changes

At this point, it should be possible to run all of the tests and ensure the bindings to the new API still work. At this point we would create a new release, etc.

**Comment by abrown** [comment]
This has been completed since the [`0.7.*`](https://github.com/intel/openvino-rs/releases/tag/v0.7.2) releases.
