### ISSUE TITLE
Make changes to adhere to Rust conventions

### ISSUE THREAD

**Issue by rahulchaphalkar** [intel/openvino-rs#95]
This issue tracks some changes that were suggested by @BTOdell while reviewing https://github.com/intel/openvino-rs/pull/91 
[This comment](https://github.com/intel/openvino-rs/pull/91#issuecomment-2035213467) details those.
Make these and similar other changes to ensure we're following proper conventions for ergonomic rust.

**Comment by abrown** [comment]
This has been completed for some time.
